import Foundation

// ExtractPromptSourceTool
// Reads a Swift source file, locates the `public static func titleInput(` function,
// extracts its complete body including braces via brace-matching, and writes a
// generated Swift file containing the body as a string constant.
//
// Usage: ExtractPromptSourceTool <input-path> <output-path>
//
// Exit codes:
//   0: success
//   1: usage error
//   2: cannot read input file
//   3: cannot find titleInput function
//   4: extracted body is empty
//   5: cannot write output file

guard CommandLine.arguments.count == 3 else {
    FileHandle.standardError.write("ExtractPromptSourceTool: usage: <input> <output>\n".data(using: .utf8)!)
    exit(1)
}
let inputPath = CommandLine.arguments[1]
let outputPath = CommandLine.arguments[2]

// 1. Read source file
guard let source = try? String(contentsOfFile: inputPath, encoding: .utf8) else {
    FileHandle.standardError.write("ExtractPromptSourceTool: cannot read \(inputPath)\n".data(using: .utf8)!)
    exit(2)
}

// 2. Locate `public static func titleInput(` and extract body via brace matching
guard let body = extractFunctionBody(from: source, signature: "public static func titleInput(") else {
    FileHandle.standardError.write("ExtractPromptSourceTool: cannot find titleInput function in \(inputPath)\n".data(using: .utf8)!)
    exit(3)
}

guard !body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
    FileHandle.standardError.write("ExtractPromptSourceTool: extracted body is empty\n".data(using: .utf8)!)
    exit(4)
}

// 3. Generate output file
// Escape backslashes first, then quotes, then newlines for safe embedding in a regular string literal
let escapedBody = body
    .replacingOccurrences(of: "\\", with: "\\\\")
    .replacingOccurrences(of: "\"", with: "\\\"")
    .replacingOccurrences(of: "\n", with: "\\n")
    .replacingOccurrences(of: "\r", with: "\\r")

let generated = """
// Auto-generated by ExtractPromptSourceTool — do not edit.
// Source: \(inputPath)
public enum GeneratedPromptSource {
    public static let titleInputFunctionSource: String = "\(escapedBody)"
}
"""

do {
    // Ensure output directory exists
    let outputURL = URL(fileURLWithPath: outputPath)
    let outputDir = outputURL.deletingLastPathComponent()
    try FileManager.default.createDirectory(at: outputDir, withIntermediateDirectories: true)
    try generated.write(toFile: outputPath, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write("ExtractPromptSourceTool: cannot write \(outputPath): \(error)\n".data(using: .utf8)!)
    exit(5)
}

// 4. Helper: extract function body by brace matching
func extractFunctionBody(from source: String, signature: String) -> String? {
    guard let signatureRange = source.range(of: signature) else { return nil }

    // Find the opening brace after the signature
    let afterSignature = source[signatureRange.upperBound...]
    guard let openBraceIdx = afterSignature.firstIndex(of: "{") else { return nil }

    // Brace-match to find the closing brace
    var depth = 0
    var currentIdx = openBraceIdx
    var started = false

    while currentIdx < source.endIndex {
        let ch = source[currentIdx]
        if ch == "{" {
            depth += 1
            started = true
        } else if ch == "}" {
            depth -= 1
            if started && depth == 0 {
                // Found the matching close brace
                let bodyRange = openBraceIdx...currentIdx
                return String(source[bodyRange])
            }
        }
        currentIdx = source.index(after: currentIdx)
    }

    return nil  // Unbalanced braces
}
